title: Electro-man
description: Electronics • Robotics • Embedded Systems
url: "https://avishkavishwajith.github.io"
baseurl: ""
permalink: pretty

collections:
  products:
    output: true
    permalink: /products/:name/

adsense_client: ""   # later: ca-pub-xxxxxxxxxxxxxxx
contact_email: "jayawardenago@gmail.com"
linkedin_url: "http://www.linkedin.com/in/avishka-vishwajith1127"
github_url: "https://github.com/AvishkaVishwa"
