# Site Settings
title: Avishka Vishwajith
email: jayawardenago@gmail.com
description: >-
  Automation & Electronics Enthusiast portfolio. Specialized in 
  embedded systems and IoT solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://username.github.io

# Social Links
github_username: AvishkaVishwa
linkedin_username: avishka-vishwajith1127

# Build settings
remote_theme: jekyll/minima # Optional, but we use a custom layout
plugins:
  - jekyll-feed
